# Generated by Django 4.0.5 on 2022-07-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
