# Generated by Django 4.0.5 on 2022-07-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpmanager', '0002_alter_item_description_alter_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hsn_sac',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
