# Generated by Django 4.0.5 on 2022-11-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpmanager', '0005_account_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
