# Generated by Django 4.0.5 on 2022-12-06 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erpmanager', '0007_purchaseorder_itemtransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='vendor',
            new_name='vendorId',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='id',
            new_name='vendorId',
        ),
    ]
