# Generated by Django 4.0.5 on 2022-12-06 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erpmanager', '0008_rename_vendor_purchaseorder_vendorid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtransaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='itemtransaction',
            name='slug',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='accountId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='erpmanager.account'),
            preserve_default=False,
        ),
    ]
