# Generated by Django 4.0.5 on 2022-12-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpmanager', '0009_remove_itemtransaction_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinPurchaseOrder',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('vendorName', models.CharField(max_length=200)),
                ('accountName', models.CharField(max_length=200)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TableColumns',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('columnName', models.CharField(max_length=200)),
            ],
        ),
    ]
