# Generated by Django 4.0.5 on 2022-12-08 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erpmanager', '0010_joinpurchaseorder_tablecolumns'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableColumns',
        ),
    ]
